parameters:

    p2_ratchet.websocket.server.class: Ratchet\WebSocket\WsServer
    p2_ratchet.server.class: Ratchet\Server\IoServer
    p2_ratchet.bridge.class: P2\Bundle\RatchetBundle\WebSocket\Bridge

    p2_ratchet.server_address: 0.0.0.0
    p2_ratchet.server_port: 8080

services:

    p2_ratchet.bridge:
        class: %p2_ratchet.bridge.class%
        arguments: [ @event_dispatcher ]

    p2_ratchet.websocket_server:
        class: %p2_ratchet.websocket.server.class%
        arguments: [ @p2_ratchet.bridge ]

    # IoServer:factory(application, port, address)
    p2_ratchet.server:
        class: %p2_ratchet.server.class%
        factory_class: %p2_ratchet.server.class%
        factory_method: factory
        arguments: [ @p2_ratchet.websocket_server, %p2_ratchet.server_port%, %p2_ratchet.server_address% ]


    echo_app:
        class: P2\Bundle\RatchetBundle\WebSocket\Application\EchoApplication
        tags:
            - { name: 'kernel.event_subscriber' }